// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChicGE4oaRth_AbuL7HQ90OawYq-_6zdw',
    appId: '1:556993387901:web:5aecadece8200baae88014',
    messagingSenderId: '556993387901',
    projectId: 'ditonton-8c3d8',
    authDomain: 'ditonton-8c3d8.firebaseapp.com',
    storageBucket: 'ditonton-8c3d8.appspot.com',
    measurementId: 'G-5HYPQSGZJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuYBJSYI0OrnVbNJvHHpGJOxE-k-1auAY',
    appId: '1:556993387901:android:e0c67476f4bbefa4e88014',
    messagingSenderId: '556993387901',
    projectId: 'ditonton-8c3d8',
    storageBucket: 'ditonton-8c3d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuuRJhvtIKNqLjDu2omVjaGnVmqDOPQfk',
    appId: '1:556993387901:ios:4c68b934790593ade88014',
    messagingSenderId: '556993387901',
    projectId: 'ditonton-8c3d8',
    storageBucket: 'ditonton-8c3d8.appspot.com',
    iosClientId: '556993387901-t8vp6ldj1aoe5p21krp0cih027kh7i5d.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
